"""Operational events generated by a NodeInstance.

ENG-013B — Node SDK
NCS reference: 17-NODE-EVENT.md
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import Enum
from types import MappingProxyType
from typing import Mapping

from app.noc.domain.node_instance import NodeInstanceId


class EventSeverity(str, Enum):
    """Canonical EventRecord severity values defined by NCS v1.0.0."""

    INFO = "INFO"
    NOTICE = "NOTICE"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

    def __str__(self) -> str:
        return self.value

    @classmethod
    def from_value(cls, value: str) -> "EventSeverity":
        if not isinstance(value, str):
            raise TypeError(
                "EventSeverity value must be a string"
            )

        normalized = value.strip().upper()

        if not normalized:
            raise ValueError(
                "EventSeverity value must not be empty"
            )

        try:
            return cls(normalized)
        except ValueError as exc:
            raise ValueError(
                f"Unsupported EventSeverity: {value!r}"
            ) from exc


@dataclass(frozen=True, slots=True)
class EventRecord:
    """Immutable record of a significant operational fact."""

    event_id: str
    event_type: str
    severity: EventSeverity
    timestamp: datetime
    source: NodeInstanceId
    title: str
    description: str
    attributes: Mapping[str, str] | None = None
    correlation_id: str | None = None

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "event_id",
            self._normalize_required_string(
                self.event_id,
                "event_id",
            ),
        )

        object.__setattr__(
            self,
            "event_type",
            self._normalize_required_string(
                self.event_type,
                "event_type",
            ).upper(),
        )

        object.__setattr__(
            self,
            "title",
            self._normalize_required_string(
                self.title,
                "title",
            ),
        )

        object.__setattr__(
            self,
            "description",
            self._normalize_required_string(
                self.description,
                "description",
            ),
        )

        if not isinstance(self.severity, EventSeverity):
            raise TypeError(
                "EventRecord.severity must be an EventSeverity"
            )

        if not isinstance(self.source, NodeInstanceId):
            raise TypeError(
                "EventRecord.source must be a NodeInstanceId"
            )

        if not isinstance(self.timestamp, datetime):
            raise TypeError(
                "EventRecord.timestamp must be a datetime"
            )

        if self.timestamp.tzinfo is None:
            raise ValueError(
                "EventRecord.timestamp must be timezone-aware and UTC"
            )

        offset = self.timestamp.utcoffset()

        if offset is None or offset != timedelta(0):
            raise ValueError(
                "EventRecord.timestamp must be expressed in UTC"
            )

        if self.correlation_id is not None:
            normalized_correlation = (
                self._normalize_optional_string(
                    self.correlation_id,
                    "correlation_id",
                )
            )

            object.__setattr__(
                self,
                "correlation_id",
                normalized_correlation,
            )

        if self.attributes is not None:
            normalized_attributes: dict[str, str] = {}

            for key, value in self.attributes.items():
                if not isinstance(key, str):
                    raise TypeError(
                        "EventRecord.attributes keys must be strings"
                    )

                if not isinstance(value, str):
                    raise TypeError(
                        "EventRecord.attributes values must be strings"
                    )

                normalized_key = key.strip()
                normalized_value = value.strip()

                if not normalized_key:
                    raise ValueError(
                        "EventRecord.attributes keys must not be empty"
                    )

                normalized_attributes[
                    normalized_key
                ] = normalized_value

            object.__setattr__(
                self,
                "attributes",
                MappingProxyType(normalized_attributes),
            )

    @property
    def is_critical(self) -> bool:
        return self.severity is EventSeverity.CRITICAL

    @property
    def is_error(self) -> bool:
        return self.severity is EventSeverity.ERROR

    @property
    def is_warning(self) -> bool:
        return self.severity is EventSeverity.WARNING

    @property
    def is_informational(self) -> bool:
        return self.severity in {
            EventSeverity.INFO,
            EventSeverity.NOTICE,
        }

    @staticmethod
    def _normalize_required_string(
        value: str,
        field_name: str,
    ) -> str:
        if not isinstance(value, str):
            raise TypeError(
                f"EventRecord.{field_name} must be a string"
            )

        normalized = value.strip()

        if not normalized:
            raise ValueError(
                f"EventRecord.{field_name} must not be empty"
            )

        return normalized

    @staticmethod
    def _normalize_optional_string(
        value: str,
        field_name: str,
    ) -> str | None:
        if not isinstance(value, str):
            raise TypeError(
                f"EventRecord.{field_name} must be a string"
            )

        normalized = value.strip()

        return normalized or None

    def __str__(self) -> str:
        return f"{self.event_type}: {self.title}"


@dataclass(frozen=True, slots=True)
class NodeEvent:
    """Collection of immutable EventRecord objects."""

    events: tuple[EventRecord, ...] = ()

    def __post_init__(self) -> None:
        if not isinstance(self.events, tuple):
            raise TypeError(
                "NodeEvent.events must be a tuple"
            )

        seen: set[str] = set()

        for event in self.events:
            if not isinstance(event, EventRecord):
                raise TypeError(
                    "NodeEvent entries must be EventRecord objects"
                )

            if event.event_id in seen:
                raise ValueError(
                    f"Duplicate event_id: {event.event_id}"
                )

            seen.add(event.event_id)

    def get(
        self,
        event_id: str,
    ) -> EventRecord | None:
        """Return an event by identifier."""
        normalized = self._normalize_event_id(event_id)

        for event in self.events:
            if event.event_id == normalized:
                return event

        return None

    def by_type(
        self,
        event_type: str,
    ) -> tuple[EventRecord, ...]:
        """Return events matching a canonical type."""
        if not isinstance(event_type, str):
            raise TypeError(
                "event_type must be a string"
            )

        normalized = event_type.strip().upper()

        if not normalized:
            raise ValueError(
                "event_type must not be empty"
            )

        return tuple(
            event
            for event in self.events
            if event.event_type == normalized
        )

    def by_severity(
        self,
        severity: EventSeverity,
    ) -> tuple[EventRecord, ...]:
        """Return events matching a severity."""
        if not isinstance(severity, EventSeverity):
            raise TypeError(
                "severity must be an EventSeverity"
            )

        return tuple(
            event
            for event in self.events
            if event.severity is severity
        )

    def by_correlation(
        self,
        correlation_id: str,
    ) -> tuple[EventRecord, ...]:
        """Return events sharing the same correlation identifier."""
        if not isinstance(correlation_id, str):
            raise TypeError(
                "correlation_id must be a string"
            )

        normalized = correlation_id.strip()

        if not normalized:
            raise ValueError(
                "correlation_id must not be empty"
            )

        return tuple(
            event
            for event in self.events
            if event.correlation_id == normalized
        )

    def __len__(self) -> int:
        return len(self.events)

    @staticmethod
    def _normalize_event_id(event_id: str) -> str:
        if not isinstance(event_id, str):
            raise TypeError(
                "event_id must be a string"
            )

        normalized = event_id.strip()

        if not normalized:
            raise ValueError(
                "event_id must not be empty"
            )

        return normalized
