"""Operational alarms generated by a NodeInstance or the NOC.

ENG-013B — Node SDK
NCS reference: 18-NODE-ALARM.md
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import Enum
from types import MappingProxyType
from typing import Mapping

from app.noc.domain.node_instance import NodeInstanceId


class AlarmSeverity(str, Enum):
    """Canonical AlarmRecord severity values defined by NCS v1.0.0."""

    INFO = "INFO"
    WARNING = "WARNING"
    MINOR = "MINOR"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"

    def __str__(self) -> str:
        return self.value

    @classmethod
    def from_value(cls, value: str) -> "AlarmSeverity":
        if not isinstance(value, str):
            raise TypeError("AlarmSeverity value must be a string")

        normalized = value.strip().upper()

        if not normalized:
            raise ValueError(
                "AlarmSeverity value must not be empty"
            )

        try:
            return cls(normalized)
        except ValueError as exc:
            raise ValueError(
                f"Unsupported AlarmSeverity: {value!r}"
            ) from exc


class AlarmState(str, Enum):
    """Canonical AlarmRecord lifecycle states defined by NCS v1.0.0."""

    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"

    def __str__(self) -> str:
        return self.value

    @classmethod
    def from_value(cls, value: str) -> "AlarmState":
        if not isinstance(value, str):
            raise TypeError("AlarmState value must be a string")

        normalized = value.strip().upper()

        if not normalized:
            raise ValueError(
                "AlarmState value must not be empty"
            )

        try:
            return cls(normalized)
        except ValueError as exc:
            raise ValueError(
                f"Unsupported AlarmState: {value!r}"
            ) from exc


@dataclass(frozen=True, slots=True)
class AlarmRecord:
    """Immutable representation of an operational alarm state."""

    alarm_id: str
    alarm_type: str
    severity: AlarmSeverity
    state: AlarmState
    timestamp: datetime
    source: NodeInstanceId
    title: str
    description: str

    acknowledged: bool = False
    acknowledged_by: str | None = None
    acknowledged_at: datetime | None = None
    resolved_at: datetime | None = None
    closed_at: datetime | None = None
    correlation_id: str | None = None
    attributes: Mapping[str, str] | None = None

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "alarm_id",
            self._normalize_required(
                self.alarm_id,
                "alarm_id",
            ),
        )

        object.__setattr__(
            self,
            "alarm_type",
            self._normalize_required(
                self.alarm_type,
                "alarm_type",
            ).upper(),
        )

        object.__setattr__(
            self,
            "title",
            self._normalize_required(
                self.title,
                "title",
            ),
        )

        object.__setattr__(
            self,
            "description",
            self._normalize_required(
                self.description,
                "description",
            ),
        )

        if not isinstance(self.severity, AlarmSeverity):
            raise TypeError(
                "AlarmRecord.severity must be an AlarmSeverity"
            )

        if not isinstance(self.state, AlarmState):
            raise TypeError(
                "AlarmRecord.state must be an AlarmState"
            )

        if not isinstance(self.source, NodeInstanceId):
            raise TypeError(
                "AlarmRecord.source must be a NodeInstanceId"
            )

        if not isinstance(self.acknowledged, bool):
            raise TypeError(
                "AlarmRecord.acknowledged must be a bool"
            )

        self._validate_utc_datetime(
            self.timestamp,
            "timestamp",
            required=True,
        )

        self._validate_utc_datetime(
            self.acknowledged_at,
            "acknowledged_at",
        )

        self._validate_utc_datetime(
            self.resolved_at,
            "resolved_at",
        )

        self._validate_utc_datetime(
            self.closed_at,
            "closed_at",
        )

        if self.acknowledged_by is not None:
            object.__setattr__(
                self,
                "acknowledged_by",
                self._normalize_optional(
                    self.acknowledged_by,
                    "acknowledged_by",
                ),
            )

        if self.correlation_id is not None:
            object.__setattr__(
                self,
                "correlation_id",
                self._normalize_optional(
                    self.correlation_id,
                    "correlation_id",
                ),
            )

        if self.attributes is not None:
            normalized: dict[str, str] = {}

            for key, value in self.attributes.items():
                if not isinstance(key, str):
                    raise TypeError(
                        "AlarmRecord.attributes keys must be strings"
                    )

                if not isinstance(value, str):
                    raise TypeError(
                        "AlarmRecord.attributes values must be strings"
                    )

                normalized_key = key.strip()
                normalized_value = value.strip()

                if not normalized_key:
                    raise ValueError(
                        "AlarmRecord.attributes keys must not be empty"
                    )

                normalized[normalized_key] = normalized_value

            object.__setattr__(
                self,
                "attributes",
                MappingProxyType(normalized),
            )

        self._validate_lifecycle_consistency()

    @property
    def is_active(self) -> bool:
        return self.state is AlarmState.ACTIVE

    @property
    def is_acknowledged(self) -> bool:
        return self.state is AlarmState.ACKNOWLEDGED

    @property
    def is_resolved(self) -> bool:
        return self.state is AlarmState.RESOLVED

    @property
    def is_closed(self) -> bool:
        return self.state is AlarmState.CLOSED

    @property
    def requires_attention(self) -> bool:
        return self.state in {
            AlarmState.ACTIVE,
            AlarmState.ACKNOWLEDGED,
        }

    def _validate_lifecycle_consistency(self) -> None:
        if self.acknowledged:
            if self.acknowledged_by is None:
                raise ValueError(
                    "acknowledged alarms require acknowledged_by"
                )

            if self.acknowledged_at is None:
                raise ValueError(
                    "acknowledged alarms require acknowledged_at"
                )

        if not self.acknowledged:
            if self.acknowledged_by is not None:
                raise ValueError(
                    "acknowledged_by requires acknowledged=True"
                )

            if self.acknowledged_at is not None:
                raise ValueError(
                    "acknowledged_at requires acknowledged=True"
                )

        if self.state is AlarmState.ACKNOWLEDGED:
            if not self.acknowledged:
                raise ValueError(
                    "ACKNOWLEDGED state requires acknowledged=True"
                )

        if self.state is AlarmState.RESOLVED:
            if self.resolved_at is None:
                raise ValueError(
                    "RESOLVED state requires resolved_at"
                )

        if self.state is AlarmState.CLOSED:
            if self.resolved_at is None:
                raise ValueError(
                    "CLOSED state requires resolved_at"
                )

            if self.closed_at is None:
                raise ValueError(
                    "CLOSED state requires closed_at"
                )

        if self.resolved_at is not None:
            if self.resolved_at < self.timestamp:
                raise ValueError(
                    "resolved_at must not precede timestamp"
                )

        if self.closed_at is not None:
            if self.resolved_at is None:
                raise ValueError(
                    "closed_at requires resolved_at"
                )

            if self.closed_at < self.resolved_at:
                raise ValueError(
                    "closed_at must not precede resolved_at"
                )

    @staticmethod
    def _normalize_required(
        value: str,
        field_name: str,
    ) -> str:
        if not isinstance(value, str):
            raise TypeError(
                f"AlarmRecord.{field_name} must be a string"
            )

        normalized = value.strip()

        if not normalized:
            raise ValueError(
                f"AlarmRecord.{field_name} must not be empty"
            )

        return normalized

    @staticmethod
    def _normalize_optional(
        value: str,
        field_name: str,
    ) -> str | None:
        if not isinstance(value, str):
            raise TypeError(
                f"AlarmRecord.{field_name} must be a string"
            )

        normalized = value.strip()

        return normalized or None

    @staticmethod
    def _validate_utc_datetime(
        value: datetime | None,
        field_name: str,
        *,
        required: bool = False,
    ) -> None:
        if value is None:
            if required:
                raise TypeError(
                    f"AlarmRecord.{field_name} must be a datetime"
                )
            return

        if not isinstance(value, datetime):
            raise TypeError(
                f"AlarmRecord.{field_name} must be a datetime"
            )

        if value.tzinfo is None:
            raise ValueError(
                f"AlarmRecord.{field_name} "
                "must be timezone-aware and UTC"
            )

        offset = value.utcoffset()

        if offset is None or offset != timedelta(0):
            raise ValueError(
                f"AlarmRecord.{field_name} must be expressed in UTC"
            )

    def __str__(self) -> str:
        return f"{self.alarm_type}: {self.title}"


@dataclass(frozen=True, slots=True)
class NodeAlarm:
    """Collection of AlarmRecord objects."""

    alarms: tuple[AlarmRecord, ...] = ()

    def __post_init__(self) -> None:
        if not isinstance(self.alarms, tuple):
            raise TypeError(
                "NodeAlarm.alarms must be a tuple"
            )

        seen: set[str] = set()

        for alarm in self.alarms:
            if not isinstance(alarm, AlarmRecord):
                raise TypeError(
                    "NodeAlarm entries must be AlarmRecord objects"
                )

            if alarm.alarm_id in seen:
                raise ValueError(
                    f"Duplicate alarm_id: {alarm.alarm_id}"
                )

            seen.add(alarm.alarm_id)

    @property
    def active(self) -> tuple[AlarmRecord, ...]:
        """Return alarms still requiring operational attention."""
        return tuple(
            alarm
            for alarm in self.alarms
            if alarm.requires_attention
        )

    @property
    def resolved(self) -> tuple[AlarmRecord, ...]:
        return tuple(
            alarm
            for alarm in self.alarms
            if alarm.state is AlarmState.RESOLVED
        )

    @property
    def closed(self) -> tuple[AlarmRecord, ...]:
        return tuple(
            alarm
            for alarm in self.alarms
            if alarm.state is AlarmState.CLOSED
        )

    def get(
        self,
        alarm_id: str,
    ) -> AlarmRecord | None:
        normalized = self._normalize_alarm_id(alarm_id)

        for alarm in self.alarms:
            if alarm.alarm_id == normalized:
                return alarm

        return None

    def by_severity(
        self,
        severity: AlarmSeverity,
    ) -> tuple[AlarmRecord, ...]:
        if not isinstance(severity, AlarmSeverity):
            raise TypeError(
                "severity must be an AlarmSeverity"
            )

        return tuple(
            alarm
            for alarm in self.alarms
            if alarm.severity is severity
        )

    def by_type(
        self,
        alarm_type: str,
    ) -> tuple[AlarmRecord, ...]:
        if not isinstance(alarm_type, str):
            raise TypeError(
                "alarm_type must be a string"
            )

        normalized = alarm_type.strip().upper()

        if not normalized:
            raise ValueError(
                "alarm_type must not be empty"
            )

        return tuple(
            alarm
            for alarm in self.alarms
            if alarm.alarm_type == normalized
        )

    def __len__(self) -> int:
        return len(self.alarms)

    @staticmethod
    def _normalize_alarm_id(alarm_id: str) -> str:
        if not isinstance(alarm_id, str):
            raise TypeError(
                "alarm_id must be a string"
            )

        normalized = alarm_id.strip()

        if not normalized:
            raise ValueError(
                "alarm_id must not be empty"
            )

        return normalized
